const ClientsData = [
  {
    serial: 1,
    previousType: '소득적격',
    applicationType: '개인전문',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인대기',
    reason: '',
    approvalDate: '',
    admin: '',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },
  {
    serial: 2,
    previousType: '소득적격',
    applicationType: '개인전문',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인거부',
    reason: '서류 식별 불가 금융투자업자에 계좌를 개설한지 1년 미만으로 전문투자자 승인 불가',
    approvalDate: '2023-01-10 09:00:00',
    admin: '김관리자',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },
  {
    serial: 3,
    previousType: '소득적격',
    applicationType: '소득적격',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인완료',
    reason: '',
    approvalDate: '2023-01-10 09:00:00',
    admin: '김관리자',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },

  {
    serial: 4,
    previousType: '소득적격',
    applicationType: '개인전문',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인대기',
    reason: '',
    approvalDate: '',
    admin: '',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },
  {
    serial: 5,
    previousType: '소득적격',
    applicationType: '개인전문',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인거부',
    reason: '서류 식별 불가 금융투자업자에 계좌를 개설한지 1년 미만으로 전문투자자 승인 불가',
    approvalDate: '2023-01-10 09:00:00',
    admin: '김관리자',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },
  {
    serial: 6,
    previousType: '소득적격',
    applicationType: '소득적격',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인완료',
    reason: '',
    approvalDate: '2023-01-10 09:00:00',
    admin: '김관리자',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },

  {
    serial: 7,
    previousType: '소득적격',
    applicationType: '개인전문',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인대기',
    reason: '',
    approvalDate: '',
    admin: '',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },
  {
    serial: 8,
    previousType: '소득적격',
    applicationType: '개인전문',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인거부',
    reason: '서류 식별 불가 금융투자업자에 계좌를 개설한지 1년 미만으로 전문투자자 승인 불가',
    approvalDate: '2023-01-10 09:00:00',
    admin: '김관리자',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },
  {
    serial: 9,
    previousType: '소득적격',
    applicationType: '소득적격',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인완료',
    reason: '',
    approvalDate: '2023-01-10 09:00:00',
    admin: '김관리자',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },

  {
    serial: 10,
    previousType: '소득적격',
    applicationType: '개인전문',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인대기',
    reason: '',
    approvalDate: '',
    admin: '',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },
  {
    serial: 11,
    previousType: '소득적격',
    applicationType: '개인전문',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인거부',
    reason: '서류 식별 불가 금융투자업자에 계좌를 개설한지 1년 미만으로 전문투자자 승인 불가',
    approvalDate: '2023-01-10 09:00:00',
    admin: '김관리자',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },
  {
    serial: 12,
    previousType: '소득적격',
    applicationType: '소득적격',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인완료',
    reason: '',
    approvalDate: '2023-01-10 09:00:00',
    admin: '김관리자',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },

  {
    serial: 13,
    previousType: '소득적격',
    applicationType: '개인전문',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인대기',
    reason: '',
    approvalDate: '',
    admin: '',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },
  {
    serial: 14,
    previousType: '소득적격',
    applicationType: '개인전문',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인거부',
    reason: '서류 식별 불가 금융투자업자에 계좌를 개설한지 1년 미만으로 전문투자자 승인 불가',
    approvalDate: '2023-01-10 09:00:00',
    admin: '김관리자',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },
  {
    serial: 15,
    previousType: '소득적격',
    applicationType: '소득적격',
    docs: '보기',
    applicationDate: '2023-01-10 09:00:00',
    approvalStatus: '승인완료',
    reason: '',
    approvalDate: '2023-01-10 09:00:00',
    admin: '김관리자',
    checked: false,
    number: '회원번호',
    name: '회원명/법인명'
  },
];

export default ClientsData;
